### ISSUE TITLE
No permite cargar esquema de impuestos

### ISSUE THREAD

**Issue by vguera** [tecnificarte/quote3.com#2]
En http://cw.efficatia.net/catalog/product/34f31420-d804-40ff-b9c5-9a09195f0baa

no permite cargar esquema de impuestos, no encontre donde cargar ese catalogo.

despues en:

http://cw.efficatia.net/quote/edit/f2a17b44-1ede-47d7-9eaf-041e6830fb39

manda este error

Error
Error en la partida 1: Falta la descripcion del impuesto

**Comment by mauleyzaola** [comment]
Sitio invalido amigo, por favor cada cosa en su repo

**Comment by Serle66** [comment]
¿Por qué me mandaste esto?

On Thu, Jun 9, 2016 at 11:19 AM, Mauricio Leyzaola <notifications@github.com

**Comment by mauleyzaola** [comment]
@sergio-leyzaola Yo no te lo mande fue github Checo. Se me habia olvidado que estabas como colaborador de este sitio.

Si no te interesa mas, puedes cancelar la subscripcion tu mismo. Si no puedes cancelarla echame un email y lo hago yo a pata. Sorry.
